# Generated by Django 4.2.5 on 2023-09-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_spaces', models.PositiveIntegerField()),
                ('available_spaces', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('night_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('Compact', 'Compact'), ('Standard', 'Standard'), ('Handicap', 'Handicap')], max_length=20)),
                ('availability', models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant')], max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarParkAPI.parkinglot')),
            ],
        ),
    ]
